import uuid
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.core.config import settings
from app.database import get_db
from app.models.platform import CloudAccount, OrgMembership, User
from app.services.cloud_service import (
    connect_aws_role_account,
    connect_azure_account,
    connect_gcp_account,
    delete_cloud_account,
    get_cloud_accounts,
    verify_cloud_account,
)

router = APIRouter(prefix="/cloud", tags=["cloud"])

AWS_REGIONS = [
    "us-east-1", "us-east-2", "us-west-1", "us-west-2",
    "eu-west-1", "eu-west-2", "eu-central-1",
    "ap-south-1", "ap-southeast-1", "ap-northeast-1",
]


class ConnectAwsRoleRequest(BaseModel):
    provider: Literal["aws"] = "aws"
    display_name: str
    role_arn: str                         # arn:aws:iam::123456789:role/LoomarisDeployRole
    region: str = "us-east-1"
    # sts_external_id is NOT supplied by the user — it's auto-generated by Loomaris per org


class ConnectAzureRequest(BaseModel):
    provider: Literal["azure"]
    display_name: str
    tenant_id: str
    client_id: str
    client_secret: str
    subscription_id: str


class ConnectGcpRequest(BaseModel):
    provider: Literal["gcp"]
    display_name: str
    project_id: str
    service_account_json: str  # raw contents of a downloaded service-account key file


def _account_out(account: CloudAccount) -> dict:
    return {
        "id": str(account.id),
        "display_name": account.display_name,
        "provider": account.provider,
        "external_id": account.external_id,       # AWS account ID
        "arn": getattr(account, "_caller_arn", None),
        "region": account.region,
        "status": account.status,
        "connection_type": account.connection_type,
        "role_arn": account.role_arn,
        "sts_external_id": account.sts_external_id,
        "last_verified_at": account.last_verified_at.isoformat() if account.last_verified_at else None,
        "created_at": account.created_at.isoformat(),
    }


async def _get_user_org_id(db: AsyncSession, user_id: uuid.UUID) -> uuid.UUID:
    result = await db.execute(
        select(OrgMembership.org_id).where(OrgMembership.user_id == user_id).limit(1)
    )
    row = result.scalar_one_or_none()
    if not row:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User has no organisation")
    return row


@router.get(
    "/setup-info",
    summary="Return Loomaris deployer ARN and org external ID for trust policy setup",
)
async def get_setup_info(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Returns the info an org admin needs to create the trust policy in their AWS console."""
    org_id = await _get_user_org_id(db, current_user.id)

    # Generate a stable per-org external ID based on the org UUID (deterministic, no extra storage)
    import hashlib
    sts_external_id = hashlib.sha256(str(org_id).encode()).hexdigest()[:32]

    loomaris_acct = settings.LOOMARIS_AWS_ACCOUNT_ID or "<LOOMARIS_AWS_ACCOUNT_ID>"
    # The ECS task role is the actual runtime principal — no long-lived keys needed.
    # Users' trust policies must trust this role ARN (not an IAM user).
    deployer_arn = f"arn:aws:iam::{loomaris_acct}:role/loomaris-ecs-task-role"

    return {
        "loomaris_deployer_arn": deployer_arn,
        "sts_external_id": sts_external_id,
        "trust_policy": {
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Principal": {"AWS": deployer_arn},
                "Action": "sts:AssumeRole",
                "Condition": {"StringEquals": {"sts:ExternalId": sts_external_id}},
            }],
        },
    }


@router.post("/accounts", summary="Connect an AWS, Azure, or GCP cloud account")
async def connect_account(
    body: ConnectAwsRoleRequest | ConnectAzureRequest | ConnectGcpRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    org_id = await _get_user_org_id(db, current_user.id)

    # Derive the stable per-org external ID
    import hashlib
    sts_external_id = hashlib.sha256(str(org_id).encode()).hexdigest()[:32]

    try:
        if isinstance(body, ConnectAwsRoleRequest):
            if body.region not in AWS_REGIONS:
                raise HTTPException(status_code=400, detail=f"Unsupported region: {body.region}")
            account = await connect_aws_role_account(
                db,
                org_id=org_id,
                display_name=body.display_name,
                role_arn=body.role_arn,
                sts_external_id=sts_external_id,
                region=body.region,
            )
        elif isinstance(body, ConnectAzureRequest):
            account = await connect_azure_account(
                db,
                org_id=org_id,
                display_name=body.display_name,
                tenant_id=body.tenant_id,
                client_id=body.client_id,
                client_secret=body.client_secret,
                subscription_id=body.subscription_id,
            )
        else:
            account = await connect_gcp_account(
                db,
                org_id=org_id,
                display_name=body.display_name,
                project_id=body.project_id,
                service_account_json=body.service_account_json,
            )
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))

    return _account_out(account)


@router.get("/accounts", summary="List cloud accounts")
async def list_accounts(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    org_id = await _get_user_org_id(db, current_user.id)
    accounts = await get_cloud_accounts(db, org_id)
    return [_account_out(a) for a in accounts]


@router.delete("/accounts/{account_id}", summary="Remove cloud account")
async def remove_account(
    account_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    org_id = await _get_user_org_id(db, current_user.id)
    await delete_cloud_account(db, account_id, org_id)
    return {"ok": True}


@router.post("/accounts/{account_id}/verify", summary="Re-verify cloud account (STS role)")
async def reverify_account(
    account_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    org_id = await _get_user_org_id(db, current_user.id)
    try:
        account = await verify_cloud_account(db, account_id, org_id)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))
    return _account_out(account)
